project_id = "vxztoizfvoilqnczfbpc"

[functions.api-proxy]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.pix-consulta]
verify_jwt = false