project_id = "vxztoizfvoilqnczfbpc"

[functions.api-proxy]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = false

[functions.pix-consulta]
verify_jwt = false

[functions.process-campaigns]
verify_jwt = false

[functions.itau-token]
verify_jwt = false

[functions.whatsapp-zapi-webhook]
verify_jwt = false

[functions.whatsapp-zapi-enviar]
verify_jwt = false

[functions.whatsapp-ia-responder]
verify_jwt = false

[functions.whatsapp-ia-sugerir]
verify_jwt = false